from __future__ import annotations

from enum import Enum


class EnvelopeState(str, Enum):
    CLOSED = "CLOSED"
    OPENING = "OPENING"
    OPEN = "OPEN"
    CLOSING = "CLOSING"


class CandidateStatus(str, Enum):
    QUALIFIED = "QUALIFIED"
    INVALIDATED = "INVALIDATED"


class SafetyState(str, Enum):
    CLEAR = "CLEAR"
    SAFETY_CLOSED = "SAFETY_CLOSED"


class SafetyReason(str, Enum):
    SHAPE_STALE = "SHAPE_STALE"
    MARKET_INELIGIBLE = "MARKET_INELIGIBLE"
    DATA_INVALID = "DATA_INVALID"
    INVALID_RETURNSHAPE = "INVALID_RETURNSHAPE"
    NO_VALID_RETURNSHAPE = "NO_VALID_RETURNSHAPE"


class EventType(str, Enum):
    RETURN_SHAPE_ACCEPTED = "RETURN_SHAPE_ACCEPTED"
    CONTEXT_REEVALUATED = "CONTEXT_REEVALUATED"
    CAPTURABILITY_EVALUATED = "CAPTURABILITY_EVALUATED"
    APERTURE_UPDATED = "APERTURE_UPDATED"
    ENVELOPE_OPENING = "ENVELOPE_OPENING"
    ENVELOPE_OPENED = "ENVELOPE_OPENED"
    ENVELOPE_CLOSING = "ENVELOPE_CLOSING"
    ENVELOPE_CLOSED = "ENVELOPE_CLOSED"
    CANDIDATE_QUALIFIED = "CANDIDATE_QUALIFIED"
    CANDIDATE_INVALIDATED = "CANDIDATE_INVALIDATED"
    SHAPE_SUPERSEDED = "SHAPE_SUPERSEDED"
    SHAPE_STALE = "SHAPE_STALE"
    DATA_INVALID = "DATA_INVALID"
    MARKET_INELIGIBLE = "MARKET_INELIGIBLE"
    INVALID_RETURNSHAPE = "INVALID_RETURNSHAPE"
    NO_VALID_RETURNSHAPE = "NO_VALID_RETURNSHAPE"

